### ISSUE TITLE
Apart from contributions most queries don't actually work

### ISSUE THREAD

**Issue by Xoeseko** [sdgsolutionspace/sdg-market-api#2]
Tried getting information like purchase information or even docs.json through the API was unsuccessful apart from getting contributions and git-projects... Here are a few examples:

    $ curl https://sdg-market.oniabsis.com/api/v1/users
    {"code":401,"message":"JWT Token not found"}

Apparently the code 401 should be for failed authentication... I am logged in to the service from the same IP... If that is not sufficient some documentation is missing to explain what should be done in order to authenticate before querying. In fact I actually think that the token has to be generated serverside for this to work... 

Would it be possible to have a token or two generated so that we can further test the api ?

**Comment by gilles-hemmerle** [comment]
The jwt token is generated when the github call back the API. This is why it is complicated to generate a token without the frontend in place. But I'm not sure this is longer an issue as you are now able to run the app locally and generate a token from the UI ? Please close the ticket if I am correct
